name: Release RapidOcrNet NuGet Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"  # 同时匹配预发布版本，如 v1.0.0-beta.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # 只在非预发布版本时发布到NuGet
    if: "!contains(github.ref, '-')"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          9.0.x
    
    - name: Set VERSION variable from tag
      run: |
        # Remove refs/tags/v prefix
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Using version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Restore dependencies
      run: dotnet restore RapidOcrNet/RapidOcrNet.csproj
    
    - name: Build
      run: dotnet build RapidOcrNet/RapidOcrNet.csproj --no-restore --configuration Release /p:Version=${VERSION}
    
    - name: Test
      run: dotnet test RapidOcrNet/RapidOcrNet.csproj --no-build --configuration Release --verbosity normal
    
    - name: Pack
      run: dotnet pack RapidOcrNet/RapidOcrNet.csproj --no-build --configuration Release /p:Version=${VERSION} --output nupkgs
    
    - name: Push to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate 